email:
    subject: 'Dagens Horoskop'
    sender_alias: 'Dina Dagliga Horoskop'

horoscopes:
    - website_name: 'Twice'
      website_url: 'http://www.dagenshoroskop.nu/horoskop/dagens/11/'
      text_xpath: '(//p)[2]'
    - website_name: 'Elle'
      website_url: 'http://astro.elle.se/'
      text_xpath: '(//p)[23]'
    - website_name: 'Magic.no'
      website_url: 'http://magic.no/horoskop?tlf=79000450&sign=11'
      text_xpath: '(//p[contains(@class, "xText")])'
    - website_name: 'Expressen - Dagshoroskop'
      website_url: 'http://www.spray.se/horoskop/vattumannen'
      text_xpath: '(//div[contains(@class, "horoscope-starsign-daily")]//p)'
    - website_name: 'Expressen - Veckohoroskop'
      website_url: 'http://www.spray.se/horoskop/vattumannen'
      text_xpath: '(//div[5]//p)'